// frontend/src/components/Header.vue
<template>
  <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-dark site-nav">
      <div class="container-fluid px-0">
        <router-link class="navbar-brand brand-mark" to="/">A Blue Rainbow</router-link>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <router-link class="nav-link" to="/">Home</router-link>
            </li>
            <li class="nav-item dropdown">
              <a 
                class="nav-link dropdown-toggle" 
                href="#" 
                role="button" 
                data-bs-toggle="dropdown" 
                aria-expanded="false"
              >
                Resources
              </a>
              <ul class="dropdown-menu">
                <li><router-link class="dropdown-item" to="/assistedliving">Assisted Living</router-link></li>
                <li><router-link class="dropdown-item" to="/homehealth">Home Health Care</router-link></li>
                <li><router-link class="dropdown-item" to="/skillednursing">Skilled Nursing</router-link></li>
                <li><router-link class="dropdown-item" to="/hospice">Hospice</router-link></li>
              </ul>
            </li>
            <li class="nav-item">
              <router-link class="nav-link" to="/feedback">Feedback</router-link>
            </li>
          </ul>
          
          <div class="d-flex align-items-center gap-3 flex-column flex-lg-row ms-lg-auto">
            <form class="d-flex top-search" action="/search" method="GET">
              <input 
                type="search" 
                class="form-control" 
                aria-label="Search" 
                placeholder="Search facilities by name" 
                name="q" 
              />
              <button class="btn btn-outline-secondary" type="submit">Search</button>
            </form>
            
            <div class="d-flex align-items-center gap-2">
              <router-link v-if="isAuthenticated" class="btn btn-light" to="/admin/facilities/new">Add Facility</router-link>
              <router-link v-if="isAuthenticated" class="btn btn-outline-light" to="/admin/users">Manage Admins</router-link>
              <router-link v-if="isAuthenticated" class="btn btn-outline-light" to="/admin/audit-logs">Audit Log</router-link>
              <span v-if="isAuthenticated" class="text-white-50 small">{{ authState.username }}</span>
              <button v-if="isAuthenticated" class="btn btn-outline-light" type="button" @click="handleLogout">Logout</button>
              <router-link v-else class="btn btn-outline-light" to="/login">Admin Login</router-link>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup>
import { useRouter } from 'vue-router'
import { authState, clearAuthSession, isAuthenticated } from '../auth'

const router = useRouter()

const handleLogout = async () => {
  clearAuthSession()
  await router.push('/')
}
</script>

// frontend/src/components/Header.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';

const Header = () => {
  return (
    <header className="site-header">
      <nav className="navbar navbar-expand-lg navbar-dark site-nav">
        <div className="container-fluid px-0">
          <Link className="navbar-brand brand-mark" to="/">A Blue Rainbow</Link>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
            <span className="navbar-toggler-icon"></span>
          </button>
          
          <div className="collapse navbar-collapse" id="mynavbar">
            <ul className="navbar-nav me-auto">
              <li className="nav-item">
                <NavLink className="nav-link" to="/">Home</NavLink>
              </li>
              <li className="nav-item dropdown">
                <a 
                  className="nav-link dropdown-toggle" 
                  href="#" 
                  role="button" 
                  data-bs-toggle="dropdown" 
                  aria-expanded="false"
                >
                  Resources
                </a>
                <ul className="dropdown-menu">
                  <li><Link className="dropdown-item" to="/assistedliving">Assisted Living</Link></li>
                  <li><Link className="dropdown-item" to="/homehealth">Home Health Care</Link></li>
                  <li><Link className="dropdown-item" to="/skillednursing">Skilled Nursing</Link></li>
                  <li><Link className="dropdown-item" to="/hospice">Hospice</Link></li>
                </ul>
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to="/feedback">Feedback</NavLink>
              </li>
            </ul>
            
            <div className="d-flex align-items-center gap-3 flex-column flex-lg-row ms-lg-auto">
              <form className="d-flex top-search" action="/search" method="GET">
                <input 
                  type="search" 
                  className="form-control" 
                  aria-label="Search" 
                  placeholder="Search facilities by name" 
                  name="q" 
                />
                <button className="btn btn-outline-secondary" type="submit">Search</button>
              </form>
              
              <div className="d-flex align-items-center gap-2">
                <Link className="btn btn-outline-light" to="/login">Admin Login</Link>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>
  );
};

export default Header;
