// frontend/src/components/HomeHealthList.vue
<template>
  <FacilityList 
    title="Home Health Agencies" 
    kicker="Care Directory"
    subtitle="Review home care providers in a more legible table and detail experience."
    :fetchData="getHomeHealth"
    detailPath="homehealth"
  />
</template>

<script setup>
import FacilityList from './FacilityList.vue'
import { getHomeHealth } from '../api'
</script>

// frontend/src/components/HomeHealthList.jsx
import React from 'react';
import FacilityList from './FacilityList';
import { getHomeHealth } from '../api';

const HomeHealthList = () => {
  return (
    <FacilityList 
      title="Home Health Providers" 
      kicker="Care Directory"
      subtitle="Review home care providers in a more legible table and detail experience."
      fetchData={getHomeHealth}
      detailPath="homehealth"
    />
  );
};

export default HomeHealthList;
