// frontend/src/components/HospiceList.jsx
import React from 'react';
import FacilityList from './FacilityList';
import { getHospice } from '../api';

const HospiceList = () => {
  return (
    <FacilityList 
      title="Hospice Care Options" 
      kicker="Care Directory"
      subtitle="Access hospice information with a calmer presentation and consistent actions."
      fetchData={getHospice}
      detailPath="hospice"
    />
  );
};

export default HospiceList;

// frontend/src/components/HospiceList.vue
<template>
  <FacilityList 
    title="Hospice Care" 
    kicker="Care Directory"
    subtitle="Access hospice information with a calmer presentation and consistent actions."
    :fetchData="getHospice"
    detailPath="hospice"
  />
</template>

<script setup>
import FacilityList from './FacilityList.vue'
import { getHospice } from '../api'
</script>
